export default {
  login: 'dangulo4',
  id: 56409526,
  node_id: 'MDQ6VXNlcjU2NDA5NTI2',
  avatar_url: 'https://avatars.githubusercontent.com/u/56409526?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/dangulo4',
  html_url: 'https://github.com/dangulo4',
  followers_url: 'https://api.github.com/users/dangulo4/followers',
  following_url: 'https://api.github.com/users/dangulo4/following{/other_user}',
  gists_url: 'https://api.github.com/users/dangulo4/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/dangulo4/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/dangulo4/subscriptions',
  organizations_url: 'https://api.github.com/users/dangulo4/orgs',
  repos_url: 'https://api.github.com/users/dangulo4/repos',
  events_url: 'https://api.github.com/users/dangulo4/events{/privacy}',
  received_events_url: 'https://api.github.com/users/dangulo4/received_events',
  type: 'User',
  site_admin: false,
  name: 'Daniel Angulo',
  company: 'Sharp Healthcare',
  blog: 'www.danielangulo.dev',
  location: 'San Diego, CA',
  email: null,
  hireable: true,
  bio: 'I offer both technical and problem-solving skills as Full Stack Developer. My passion to problem solve has led me to this path....',
  twitter_username: null,
  public_repos: 44,
  public_gists: 0,
  followers: 11,
  following: 13,
  created_at: '2019-10-10T18:19:02Z',
  updated_at: '2021-12-12T21:46:11Z',
}
