export default [
  {
    login: 'julacosta9',
    id: 8892386,
    node_id: 'MDQ6VXNlcjg4OTIzODY=',
    avatar_url: 'https://avatars.githubusercontent.com/u/8892386?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/julacosta9',
    html_url: 'https://github.com/julacosta9',
    followers_url: 'https://api.github.com/users/julacosta9/followers',
    following_url:
      'https://api.github.com/users/julacosta9/following{/other_user}',
    gists_url: 'https://api.github.com/users/julacosta9/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/julacosta9/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/julacosta9/subscriptions',
    organizations_url: 'https://api.github.com/users/julacosta9/orgs',
    repos_url: 'https://api.github.com/users/julacosta9/repos',
    events_url: 'https://api.github.com/users/julacosta9/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/julacosta9/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'NVK2016',
    id: 39390897,
    node_id: 'MDQ6VXNlcjM5MzkwODk3',
    avatar_url: 'https://avatars.githubusercontent.com/u/39390897?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/NVK2016',
    html_url: 'https://github.com/NVK2016',
    followers_url: 'https://api.github.com/users/NVK2016/followers',
    following_url:
      'https://api.github.com/users/NVK2016/following{/other_user}',
    gists_url: 'https://api.github.com/users/NVK2016/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/NVK2016/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/NVK2016/subscriptions',
    organizations_url: 'https://api.github.com/users/NVK2016/orgs',
    repos_url: 'https://api.github.com/users/NVK2016/repos',
    events_url: 'https://api.github.com/users/NVK2016/events{/privacy}',
    received_events_url: 'https://api.github.com/users/NVK2016/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'CornveliousFarva',
    id: 51144146,
    node_id: 'MDQ6VXNlcjUxMTQ0MTQ2',
    avatar_url: 'https://avatars.githubusercontent.com/u/51144146?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/CornveliousFarva',
    html_url: 'https://github.com/CornveliousFarva',
    followers_url: 'https://api.github.com/users/CornveliousFarva/followers',
    following_url:
      'https://api.github.com/users/CornveliousFarva/following{/other_user}',
    gists_url: 'https://api.github.com/users/CornveliousFarva/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/CornveliousFarva/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/CornveliousFarva/subscriptions',
    organizations_url: 'https://api.github.com/users/CornveliousFarva/orgs',
    repos_url: 'https://api.github.com/users/CornveliousFarva/repos',
    events_url:
      'https://api.github.com/users/CornveliousFarva/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/CornveliousFarva/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'lokisixonenine',
    id: 53311979,
    node_id: 'MDQ6VXNlcjUzMzExOTc5',
    avatar_url: 'https://avatars.githubusercontent.com/u/53311979?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/lokisixonenine',
    html_url: 'https://github.com/lokisixonenine',
    followers_url: 'https://api.github.com/users/lokisixonenine/followers',
    following_url:
      'https://api.github.com/users/lokisixonenine/following{/other_user}',
    gists_url: 'https://api.github.com/users/lokisixonenine/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/lokisixonenine/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/lokisixonenine/subscriptions',
    organizations_url: 'https://api.github.com/users/lokisixonenine/orgs',
    repos_url: 'https://api.github.com/users/lokisixonenine/repos',
    events_url: 'https://api.github.com/users/lokisixonenine/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/lokisixonenine/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'collinkier',
    id: 55360233,
    node_id: 'MDQ6VXNlcjU1MzYwMjMz',
    avatar_url: 'https://avatars.githubusercontent.com/u/55360233?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/collinkier',
    html_url: 'https://github.com/collinkier',
    followers_url: 'https://api.github.com/users/collinkier/followers',
    following_url:
      'https://api.github.com/users/collinkier/following{/other_user}',
    gists_url: 'https://api.github.com/users/collinkier/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/collinkier/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/collinkier/subscriptions',
    organizations_url: 'https://api.github.com/users/collinkier/orgs',
    repos_url: 'https://api.github.com/users/collinkier/repos',
    events_url: 'https://api.github.com/users/collinkier/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/collinkier/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'lglasser87',
    id: 58155758,
    node_id: 'MDQ6VXNlcjU4MTU1NzU4',
    avatar_url: 'https://avatars.githubusercontent.com/u/58155758?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/lglasser87',
    html_url: 'https://github.com/lglasser87',
    followers_url: 'https://api.github.com/users/lglasser87/followers',
    following_url:
      'https://api.github.com/users/lglasser87/following{/other_user}',
    gists_url: 'https://api.github.com/users/lglasser87/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/lglasser87/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/lglasser87/subscriptions',
    organizations_url: 'https://api.github.com/users/lglasser87/orgs',
    repos_url: 'https://api.github.com/users/lglasser87/repos',
    events_url: 'https://api.github.com/users/lglasser87/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/lglasser87/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'JBanuelos00',
    id: 58202151,
    node_id: 'MDQ6VXNlcjU4MjAyMTUx',
    avatar_url: 'https://avatars.githubusercontent.com/u/58202151?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/JBanuelos00',
    html_url: 'https://github.com/JBanuelos00',
    followers_url: 'https://api.github.com/users/JBanuelos00/followers',
    following_url:
      'https://api.github.com/users/JBanuelos00/following{/other_user}',
    gists_url: 'https://api.github.com/users/JBanuelos00/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/JBanuelos00/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/JBanuelos00/subscriptions',
    organizations_url: 'https://api.github.com/users/JBanuelos00/orgs',
    repos_url: 'https://api.github.com/users/JBanuelos00/repos',
    events_url: 'https://api.github.com/users/JBanuelos00/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/JBanuelos00/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'amyfabella',
    id: 58534390,
    node_id: 'MDQ6VXNlcjU4NTM0Mzkw',
    avatar_url: 'https://avatars.githubusercontent.com/u/58534390?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/amyfabella',
    html_url: 'https://github.com/amyfabella',
    followers_url: 'https://api.github.com/users/amyfabella/followers',
    following_url:
      'https://api.github.com/users/amyfabella/following{/other_user}',
    gists_url: 'https://api.github.com/users/amyfabella/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/amyfabella/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/amyfabella/subscriptions',
    organizations_url: 'https://api.github.com/users/amyfabella/orgs',
    repos_url: 'https://api.github.com/users/amyfabella/repos',
    events_url: 'https://api.github.com/users/amyfabella/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/amyfabella/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Mbell42',
    id: 58577031,
    node_id: 'MDQ6VXNlcjU4NTc3MDMx',
    avatar_url: 'https://avatars.githubusercontent.com/u/58577031?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Mbell42',
    html_url: 'https://github.com/Mbell42',
    followers_url: 'https://api.github.com/users/Mbell42/followers',
    following_url:
      'https://api.github.com/users/Mbell42/following{/other_user}',
    gists_url: 'https://api.github.com/users/Mbell42/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Mbell42/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Mbell42/subscriptions',
    organizations_url: 'https://api.github.com/users/Mbell42/orgs',
    repos_url: 'https://api.github.com/users/Mbell42/repos',
    events_url: 'https://api.github.com/users/Mbell42/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Mbell42/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'steppenbar',
    id: 58578156,
    node_id: 'MDQ6VXNlcjU4NTc4MTU2',
    avatar_url: 'https://avatars.githubusercontent.com/u/58578156?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/steppenbar',
    html_url: 'https://github.com/steppenbar',
    followers_url: 'https://api.github.com/users/steppenbar/followers',
    following_url:
      'https://api.github.com/users/steppenbar/following{/other_user}',
    gists_url: 'https://api.github.com/users/steppenbar/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/steppenbar/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/steppenbar/subscriptions',
    organizations_url: 'https://api.github.com/users/steppenbar/orgs',
    repos_url: 'https://api.github.com/users/steppenbar/repos',
    events_url: 'https://api.github.com/users/steppenbar/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/steppenbar/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'carabunnell',
    id: 58709037,
    node_id: 'MDQ6VXNlcjU4NzA5MDM3',
    avatar_url: 'https://avatars.githubusercontent.com/u/58709037?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/carabunnell',
    html_url: 'https://github.com/carabunnell',
    followers_url: 'https://api.github.com/users/carabunnell/followers',
    following_url:
      'https://api.github.com/users/carabunnell/following{/other_user}',
    gists_url: 'https://api.github.com/users/carabunnell/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/carabunnell/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/carabunnell/subscriptions',
    organizations_url: 'https://api.github.com/users/carabunnell/orgs',
    repos_url: 'https://api.github.com/users/carabunnell/repos',
    events_url: 'https://api.github.com/users/carabunnell/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/carabunnell/received_events',
    type: 'User',
    site_admin: false,
  },
]
